version: '3.8'

services:
  my-axum-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@192.168.1.186:27017
